---
deployment:
  tasks:
    - cd /home/apasltashkent/repositories/Apasl/
    - npm install
    - npm run build
    - export DEPLOYPATH=/home/apasltashkent/public_html/
    - /bin/rm -rf $DEPLOYPATH*
    - /bin/cp -R build/* $DEPLOYPATH
